### ISSUE TITLE
Los Redimidos

### ISSUE THREAD

**Issue by perringaiden** [perringaiden/IngressPortalAppeals#60]
https://plus.google.com/+gramzeta/posts/WtR4R3S4q5Z

Appeal Category: Rejected Submission

Portal Title: Los Redimidos
Submitted: 2015/2/9
Rejected: 2017/8/3

City, Region and Country: Poeta Sansano, 8 Alicante 03010 Spain
Lat/Long: 38.364156, -0.493444

Reason/comments: Based on the Candidate Portal criteria section: Public places of worship.

The portal picture lacks of surroundings because they aren't visually impressive and it's mainly focused on the churchgoers community placard.

I also appeal to the terms: "[...] a special nod to industries and networks that connect people around the world" and "[...] candidates do not necessarily have to be visually impressive to meet our acceptance criteria."

GMaps link: https://goo.gl/maps/qHkS4vksVL32
Ingress Intel Link: https://www.ingress.com/intel?ll=38.363828,-0.49306&z=19

Thank you for your time.

Best regards.

@gr4m

**Comment by perringaiden** [comment]
Agent, your submission was rejected based on the votes by fellow Agents in the OPR community. If you believe this candidate meets the criteria (https://support.ingress.com/hc/articles/207343987) and should have been accepted, re-submit the Portal candidate at the right location.

**Comment by gr4m** [comment]
Thank you for time with this issue. I'm not going to reappeal, because I
believe that the result will be the same. On the other hand, you should
modify the portal criteria to this new point: if a portal meets the
criteria but opr democracy don't like it, it doesn't matter what the portal
criteria says.

Regards
